<?php
/**
 * @var MercadoPago\Core\Block\CustomTicket\Success $block
 */
$order = $this->getOrder();
$total = $this->getTotal();
$payment = $this->getPayment();

$payment_method = $this->getPaymentMethod();
$info_payment = $this->getInfoPayment();

$accountCreated = $this->getAccountCreatedVisible();
?>

<div id="box-mercadopago">

    <?php if ($payment_method == 'mercadopago_customticket'): ?>
        <h2 class="general-subtitle"><?php /* @escapeNotVerified */ echo __('Thank you for your purchase!'); ?></h2>

        <p id="order-generated">
            <?php /* @escapeNotVerified */ echo __(
                'Your order %1 has been successfully generated.',
                '<a href="' . $block->escapeUrl($this->getOrderUrl()) . '">' . $block->escapeHtml($order->getIncrementId()) . '</a>'
            ); ?>
            <?php if ($accountCreated){?>
                <br/>También te enviamos otro e-mail de bienvenida con tus datos de identificación<br/>para que en tus próximas visitas puedas ganar tiempo comprando más rápido.
            <?php }?>
        </p>

        <p>
            <?php echo __('Generate the ticket and pay it wherever you want.'); ?>
            <br/>
            <?php /* @escapeNotVerified */ echo __('Will be approved within 2 business days.'); ?>
        </p>
        <a href="<?php echo $block->escapeUrl(urldecode($payment->getAdditionalInformation('activation_uri'))); ?>"
           target="_blank" id="btn-boleto-mercadopago" class="button-primary">
            <?php /* @escapeNotVerified */ echo __('Generate Ticket'); ?>
        </a>

    <?php endif; ?>

</div>

<div id="logo-mercadopago">
    <img src="https://secure.mlstatic.com/components/resources/mp/desktop/css/assets/desktop-logo-mercadopago.png"/>
    <img src="/media/onestepcheckout/protegida.png" class="protegida"/>
</div>

<div class="primary button-success">
    <p>
        Una vez que el pago se haya acreditado coordinaremos la entrega.<br/>
        Por cualquier duda o consulta no dejes de comunicarte con nosotros.
    </p>
    <a href="<?php echo $block->escapeUrl($block->getUrl()) ?>"><span><u><?php /* @escapeNotVerified */ echo __('Volver a la home') ?></u></span></a>
</div>
