<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
$_post         = $this->getPost();
$_publishDate  = date("d/m/Y", strtotime($_post->getPublishTime()));
$_postUrl      = $_post->getPostUrl();
$_postName     = $block->escapeHtml($_post->getTitle(), null, true);
$featuredImage = $_post->getFeaturedImage();
$_shortContent = substr(strip_tags($_post->getContent()), 0, 92) ."...";

$_config           = $this->helper('Sm\Market\Helper\Data');
$enableLadyLoading = $_config->getAdvanced('enable_ladyloading');
$mediaSrc          = $_config->getMediaUrl();
if ($enableLadyLoading) {
    $imgClass = 'lazyload';
} else {
    $imgClass = '';
}
?>
<li class="post-holder <?php if ($featuredImage) echo 'image-featured-post'; ?> post-holder-<?php echo $_post->getId() ?>" style="width: 100%;">
    <div class="post-content">
        <div class="post-description clearfix">
            <?php if ($featuredImage) { ?>
                <div class="post-ftimg-hld static-image">
                    <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                        <img class="<?php echo $imgClass; ?>"
                            <?php if ($enableLadyLoading) { ?>
                                src="<?php echo $mediaSrc . 'lazyloading/blank.png'; ?>"
                                data-src="<?php echo $featuredImage ?>"
                            <?php } else { ?>
                                src="<?php echo $featuredImage ?>"
                            <?php } ?>

                             alt="<?php echo $_postName ?>"
                        />
                    </a>
                </div>
            <?php } ?>

            <div class="post-text-hld">
                <h2 class="post-title">
                    <a class="post-item-link"
                       href="<?php echo $_postUrl ?>">
                        <?php echo $_postName; ?>
                    </a>
                </h2>
                <span class="post-publish-date"><?php echo $_publishDate; ?></span>

                <p><?php echo $_shortContent; ?></p>
            </div>
        </div>
    </div>
</li>