<div class="header-container header-style-9">
	<div class="header-top">
		<div class="container">
			<div class="row row-topheader">
				<div class="col-lg-4 col-md-4 col-sm-3 language-currency-header">
					<?php echo $block->getChildHtml('language-header'); ?>
					<?php echo $block->getChildHtml('currency-header'); ?>
				</div>

				<div class="col-lg-8 col-md-8 col-sm-9 header-top-links">
					<?php echo $block->getChildHtml('toplinks-header'); ?>
				</div>
			</div>
		</div>
	</div>

	<div class="header-middle">
		<div class="container">
			<div class="middle-content">
				<div class="row">
					<div class="col-lg-3 logo-header">
						<?php echo $block->getChildHtml('logo_theme'); ?>
					</div>

					<div class="col-lg-9 header-middle-right">
						<div class="minicart-header">
							<div class="minicart-content">
								<?php echo $block->getChildHtml('cart-header'); ?>
							</div>
						</div>

						<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('phone-header-v5')->toHtml(); ?>

                        <div class="search-header">
							<?php echo $block->getChildHtml('search-header-pro'); ?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

    <div class="header-bottom">
        <div class="container">
            <img class="logo-ontop" width="100px" style="display: none;margin-right:10px;float:left" src="<?php echo $block->getViewFileUrl('images/logo-ontop.png') ?>" alt="Weinert"/>
            <div class="row">
                <div class="main-megamenu">
                    <div class="menu-full">
                        <?php
                        if ($_config->getGeneral('menu_style') == 'megamenu') {
                            echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml();
                        } else {
                            echo $block->getChildHtml('navigation-header');
                        }
                        ?>
                    </div>

                    <div class="navigation-mobile-container">
                        <?php echo $block->getChildHtml('navigation.mobile'); ?>
                    </div>

                </div>

                <div class="link-right minicart">

                </div>
            </div>
        </div>
    </div>

</div>
