<?php $availableSocials = $block->getAvailableSocials(); ?>
<?php $authenConfig = $block->getSocialButtonsConfig(); ?>
<?php if ($block->canShow(\Sm\SocialLogin\Model\System\Config\Source\Position::PAGE_AUTHEN) && sizeof($availableSocials)): ?>
    <script>
        window.socialAuthenticationPopup = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($authenConfig); ?>;
    </script>
<?php endif; ?>
