<div class="header-container header-style-checkout">
    <div class="header-middle">
        <div class="container">
            <div class="middle-content">
                <div class="row-header">
                    <div class="logo-header">
                        <?php echo $block->getChildHtml('logo-header'); ?>
                    </div>
                    <div class="safe-site-col">
                        <div class="safe-site">
                            <img src="/media/onestepcheckout/https_black.png"/>
                            <span>Sitio seguro</span>
                        </div>
                    </div>
                    <br clear="all"/>
                </div>
            </div>
        </div>
    </div>
</div>