<?php $_shipment = $block->getShipment() ?>
<?php $_order = $block->getOrder() ?>
<?php if ($_shipment && $_order && $_shipment->getAllTracks()): ?>
    <br />
    <table class="shipment-track">
        <thead>
        <tr>
            <th><?= /* @escapeNotVerified */  __('Shipped By') ?></th>
            <th><?= /* @escapeNotVerified */  __('Tracking Number') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($_shipment->getAllTracks() as $_item): ?>
            <tr>
                <td><?= $block->escapeHtml($_item->getTitle()) ?>:</td>

                <?php if(strpos($_item->getCarrierCode(),'andreani') !== false):?>
                    <td><a href="http://seguimiento.andreani.com/envio/<?= $block->escapeHtml($_item->getNumber()) ?>"><?= $block->escapeHtml($_item->getNumber()) ?></a></td>
                <?php else: ?>
                    <td><?= $block->escapeHtml($_item->getNumber()) ?></td>
                <?php endif; ?>

            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
<?php endif; ?>
