<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="block block-customer-login" style="position: relative;">
    <div id="login-loader" class="loading-mask" style="position: absolute; display:none;">
        <div class="loader">
            <img src="<?php echo $this->getViewFileUrl('images/loader-1.gif'); ?>" alt="Loading..." style="position: absolute;">
        </div>
    </div>
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Registered Customers')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login">
                <div class="field note"><?= $block->escapeHtml(__('If you have an account, sign in with your email address.')) ?></div>
                <div class="field email required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="useremail" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> class="input-text" id="userpass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="primary"><button type="submit" class="action login primary button-primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div>
                    <div class="secondary"><a id="send_new_password" class="action remind button-secondary" href="#" onclick="return false;"><span><?= $block->escapeHtml(__('Quiero recibir la contraseña por mail')) ?></span></a></div>
                </div>

                <p class="password-sent">
                    <img src="/media/onestepcheckout/check-ok-jse.gif" class="image-check">
                    <span>Listo!, te acabamos de enviar una nueva contraseña a tu mail</span>
                </p>
            </fieldset>
        </form>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#login-form": {
            "Sm_Market/js/customerLogin": {}
        }
    }
</script>
